downgrading docker-client dependency to v19.03.8 due to client-server incompatibility
- error msg:

   Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40
   2021-03-25 22:56:30 ERROR hydra hydra.go:61 Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40
   panic: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40